kind: Service
apiVersion: v1
metadata:
  name: notification
spec:
  selector:
    app: notification
    version: latest
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
  type: ClusterIP
