
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'codelab-monitor'

rule_files:

scrape_configs:
  - job_name: 'api-gateway'
    scrape_interval: 5s
    metrics_path: '/prometheus' 
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/keystore.crt
      insecure_skip_verify: true
    static_configs:
      - targets: ['api-gateway:443']
  - job_name: 'user-service'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['user:9001']
  - job_name: 'post-service'
    scrape_interval: 5s
    metrics_path: '/prometheus' 
    static_configs:
      - targets: ['post:9002']
  - job_name: 'authentication-service'
    scrape_interval: 5s
    metrics_path: '/prometheus' 
    static_configs:
      - targets: ['authentication:9005']